### ISSUE TITLE
Seems to have been broken by HA 0.115.1

### ISSUE THREAD

**Issue by cerebrate** [xannor/hass_weather_template#1]
Weather entity no longer appears, and the following error shows up on checking the configuration:

_Platform error weather.weather_template - cannot import name 'extract_entities' from 'homeassistant.components.template' (/usr/src/homeassistant/homeassistant/components/template/__init__.py)_

**Comment by xannor** [comment]
It looks like the template changes in 1.115 removed a lot of the old ways to do templates. Will have to research how they need to be done now.

**Comment by xannor** [comment]
I released a new version with fixes that work in my current 116.0 build. I hadn't re set this up after I moved my hardware so I did not notice that the 115 build broke it. If there are any further problems let me know.
